# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-06 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='story',
            field=models.TextField(default='story'),
            preserve_default=False,
        ),
    ]
