# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0006_auto_20170711_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='parent_location',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
