# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-11 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0007_place_parent_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_name',
            new_name='name',
        ),
    ]
