# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-11 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0008_auto_20170711_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(default='Eleros', max_length=25),
            preserve_default=False,
        ),
    ]
