# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0010_place_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tradegood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('goods_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
