# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-12 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0012_auto_20170712_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='appearance',
            new_name='quote',
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(default='Religion', max_length=50),
            preserve_default=False,
        ),
    ]
