# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-12 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0014_place_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='image_name',
            field=models.CharField(default='culture', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='image_name',
            field=models.CharField(default='organization', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='image_name',
            field=models.CharField(default='person', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradegood',
            name='image_name',
            field=models.CharField(default='tradegood', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workofart',
            name='image_name',
            field=models.CharField(default='famouswork', max_length=75),
            preserve_default=False,
        ),
    ]
