# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-13 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0016_auto_20170712_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culture',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('question_number',)},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='tradegood',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='workofart',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='tile',
            name='organization_1',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='organization_2',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='tradegood_1',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='tradegood_2',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='tradegood_3',
        ),
        migrations.AddField(
            model_name='tile',
            name='tradegoods',
            field=models.ManyToManyField(to='tile_map.Tradegood'),
        ),
    ]
