# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-13 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0018_place_tiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='appearance',
        ),
    ]
