# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-14 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0019_remove_place_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='organizations',
            field=models.ManyToManyField(to='tile_map.Organization'),
        ),
    ]
