# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-14 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0021_auto_20170714_0240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tile',
            options={'ordering': ('id',)},
        ),
    ]
