# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-14 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0022_auto_20170714_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='related_places',
            field=models.ManyToManyField(to='tile_map.Place'),
        ),
    ]
