# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-14 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0025_auto_20170714_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='location',
        ),
        migrations.AddField(
            model_name='person',
            name='locations',
            field=models.ManyToManyField(to='tile_map.Place'),
        ),
    ]
