# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-17 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0026_auto_20170714_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rent_loc',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='tile_map.Place'),
            preserve_default=False,
        ),
    ]
