# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-17 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0027_place_rent_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='world',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
