# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-17 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0029_auto_20170717_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='parent_location',
        ),
        migrations.AlterField(
            model_name='place',
            name='is_world',
            field=models.BooleanField(verbose_name="Is this place your 'World' in which all other locations exist?"),
        ),
    ]
