# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-17 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0033_auto_20170717_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, upload_to='place_imgs'),
        ),
    ]
