# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-18 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0034_auto_20170717_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
    ]
