# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-18 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile_map', '0035_remove_place_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='location',
        ),
        migrations.AddField(
            model_name='organization',
            name='locations',
            field=models.ManyToManyField(to='tile_map.Tile'),
        ),
        migrations.AlterField(
            model_name='person',
            name='locations',
            field=models.ManyToManyField(to='tile_map.Tile'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='relevant_places',
            field=models.ManyToManyField(blank=True, to='tile_map.Place'),
        ),
    ]
